name: DOCS to Server

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/zebra-swiper-docs/**
      - example/cli/**

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build H5 for example-cli
        run: pnpm run build:h5
        working-directory: example/cli

      - name: Copy H5 build vitepress
        run: cp -r example/cli/dist/build/h5 docs/zebra-swiper-docs/public

      - name: Build Site
        run: pnpm run docs:build
        working-directory: docs/zebra-swiper-docs

      - name: Upload File via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'docs/zebra-swiper-docs/.vitepress/dist/*'
          target: '/www/wwwroot/swiper.zebraui.com/dist'
          strip_components: 3
          rm: true
